#!/usr/bin/env node
// TLS sibling of serve.mjs for the web-compat client-cert behavior spec
// (M14 F1 L3, flight DD6): an HTTPS server that REQUESTS a client certificate
// on the handshake (`requestCert: true`) without requiring one
// (`rejectUnauthorized: false`), so both spec outcomes are reachable:
//   - cert presented  → page body carries #auth-state = client-cert-presented
//   - no cert         → page body carries #auth-state = no-client-cert
//
// Serves the throwaway certs generated by gen-certs.mjs (./certs/, gitignored)
// and fails loudly with the regeneration hint when they are missing. Loopback
// bind only; JSONL log format matches serve.mjs (presence booleans only —
// never certificate contents).
//
// Usage: node serve-tls.mjs --port <port> [--log <path>] [--cert-set untrusted|trusted]
// `--cert-set` (Mission 20 Flight 2 Leg 4, DD14) selects which fixture cert
// set to present: `untrusted` (default, unchanged — CA #1, never imported as
// a trust anchor) or `trusted` (CA #2 — `server-trusted.pem`, trusted ONLY
// after `node import-trust-anchor.mjs --import`).
// Verify (per the leg's Verification Steps, from ./certs/):
//   curl -k --cert client.pem --key client-key.pem https://127.0.0.1:<port>/   → authenticated marker
//   curl -k https://127.0.0.1:<port>/                                          → unauthenticated state
//   curl --cacert trusted-ca.pem https://127.0.0.1:<port>/  (--cert-set trusted) → succeeds WITHOUT -k

import https from 'node:https';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const certsDir = path.join(here, 'certs');

function parseArgs(argv) {
  const args = { port: null, log: null, certSet: 'untrusted' };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--port') args.port = Number(argv[++i]);
    else if (argv[i] === '--log') args.log = argv[++i];
    else if (argv[i] === '--cert-set') args.certSet = argv[++i];
  }
  if (!args.port) {
    console.error('Usage: node serve-tls.mjs --port <port> [--log <path>] [--cert-set untrusted|trusted]');
    process.exit(1);
  }
  if (args.certSet !== 'untrusted' && args.certSet !== 'trusted') {
    console.error('serve-tls: --cert-set must be "untrusted" (default) or "trusted"');
    process.exit(1);
  }
  return args;
}

const { port, log: logPath, certSet } = parseArgs(process.argv.slice(2));

if (logPath) fs.writeFileSync(logPath, '');
function appendLog(entry) {
  if (logPath) fs.appendFileSync(logPath, JSON.stringify(entry) + '\n');
}

function readCert(name) {
  try {
    return fs.readFileSync(path.join(certsDir, name));
  } catch {
    console.error(
      `serve-tls: missing ${name} in ${certsDir} — run \`node tests/behavior/fixtures/web-compat/gen-certs.mjs\` first (certs are gitignored, regenerated locally).`
    );
    process.exit(1);
  }
}

// Mission 20 Flight 2 Leg 4 (DD14): the trusted set is byte-identical in
// SHAPE to the default (same SAN, same server cert role) — only the signing
// CA differs, so serve-tls.mjs's own request handling never branches on
// certSet again below this point.
const key = readCert(certSet === 'trusted' ? 'server-trusted-key.pem' : 'server-key.pem');
const leafCert = readCert(certSet === 'trusted' ? 'server-trusted.pem' : 'server.pem');
const ca = readCert(certSet === 'trusted' ? 'trusted-ca.pem' : 'ca.pem');
// Mission 20 Flight 2 Leg 4 (live-discovered, TLS-trust behavior spec): `cert`
// carries the FULL CHAIN (leaf + issuing CA), not the leaf alone. A bare leaf
// PEM (the shape every prior fixture use needed) never gives Chromium a chain
// to report at all — `tls`'s own `cert` option accepts "the PEM formatted
// certificate ... followed by the PEM formatted intermediate certificates"
// concatenated, exactly what the TLS-trust behavior spec's certificate-viewer
// rows need to exercise a real two-level chain (server → CA). `ca` keeps its
// existing, UNRELATED role below (verifying a PRESENTED client certificate,
// client-cert leg F1 L3) — unaffected by what the server now sends the peer.
const cert = Buffer.concat([leafCert, ca]);

function page(authState) {
  return `<!doctype html>
<html>
<head><meta charset="utf-8"><title>web-compat client-cert fixture</title></head>
<body>
  <h1>Client-certificate fixture</h1>
  <p>Auth state: <span id="auth-state">${authState}</span></p>
</body>
</html>
`;
}

const server = https.createServer(
  // requestCert asks for a client cert on every handshake; rejectUnauthorized
  // false lets cert-less handshakes complete so the fixture can serve the
  // DISTINGUISHABLE unauthenticated state instead of a connection reset.
  { key, cert, ca, requestCert: true, rejectUnauthorized: false },
  (req, res) => {
    const peer = req.socket.getPeerCertificate();
    const presented = peer != null && typeof peer === 'object' && Object.keys(peer).length > 0;
    // Log presence/authorization booleans only — never certificate contents
    // (the serve.mjs auth-header discipline).
    appendLog({
      ts: new Date().toISOString(),
      path: req.url,
      clientCertPresented: presented,
      clientCertAuthorized: req.socket.authorized === true,
    });
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
    res.end(page(presented ? 'client-cert-presented' : 'no-client-cert'));
  }
);

server.listen(port, '127.0.0.1', () => {
  console.log(
    `web-compat TLS fixture server listening on https://127.0.0.1:${port} (requestCert: true, --cert-set ${certSet})`
  );
});
