#!/usr/bin/env node
// TLS sibling of serve.mjs for the web-compat client-cert behavior spec
// (M14 F1 L3, flight DD6): an HTTPS server that REQUESTS a client certificate
// on the handshake (`requestCert: true`) without requiring one
// (`rejectUnauthorized: false`), so both spec outcomes are reachable:
//   - cert presented  → page body carries #auth-state = client-cert-presented
//   - no cert         → page body carries #auth-state = no-client-cert
//
// Serves the throwaway certs generated by gen-certs.mjs (./certs/, gitignored)
// and fails loudly with the regeneration hint when they are missing. Loopback
// bind only; JSONL log format matches serve.mjs (presence booleans only —
// never certificate contents).
//
// Usage: node serve-tls.mjs --port <port> [--log <path>]
// Verify (per the leg's Verification Steps, from ./certs/):
//   curl -k --cert client.pem --key client-key.pem https://127.0.0.1:<port>/   → authenticated marker
//   curl -k https://127.0.0.1:<port>/                                          → unauthenticated state

import https from 'node:https';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const certsDir = path.join(here, 'certs');

function parseArgs(argv) {
  const args = { port: null, log: null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--port') args.port = Number(argv[++i]);
    else if (argv[i] === '--log') args.log = argv[++i];
  }
  if (!args.port) {
    console.error('Usage: node serve-tls.mjs --port <port> [--log <path>]');
    process.exit(1);
  }
  return args;
}

const { port, log: logPath } = parseArgs(process.argv.slice(2));

if (logPath) fs.writeFileSync(logPath, '');
function appendLog(entry) {
  if (logPath) fs.appendFileSync(logPath, JSON.stringify(entry) + '\n');
}

function readCert(name) {
  try {
    return fs.readFileSync(path.join(certsDir, name));
  } catch {
    console.error(
      `serve-tls: missing ${name} in ${certsDir} — run \`node tests/behavior/fixtures/web-compat/gen-certs.mjs\` first (certs are gitignored, regenerated locally).`
    );
    process.exit(1);
  }
}

const key = readCert('server-key.pem');
const cert = readCert('server.pem');
const ca = readCert('ca.pem');

function page(authState) {
  return `<!doctype html>
<html>
<head><meta charset="utf-8"><title>web-compat client-cert fixture</title></head>
<body>
  <h1>Client-certificate fixture</h1>
  <p>Auth state: <span id="auth-state">${authState}</span></p>
</body>
</html>
`;
}

const server = https.createServer(
  // requestCert asks for a client cert on every handshake; rejectUnauthorized
  // false lets cert-less handshakes complete so the fixture can serve the
  // DISTINGUISHABLE unauthenticated state instead of a connection reset.
  { key, cert, ca, requestCert: true, rejectUnauthorized: false },
  (req, res) => {
    const peer = req.socket.getPeerCertificate();
    const presented = peer != null && typeof peer === 'object' && Object.keys(peer).length > 0;
    // Log presence/authorization booleans only — never certificate contents
    // (the serve.mjs auth-header discipline).
    appendLog({
      ts: new Date().toISOString(),
      path: req.url,
      clientCertPresented: presented,
      clientCertAuthorized: req.socket.authorized === true,
    });
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
    res.end(page(presented ? 'client-cert-presented' : 'no-client-cert'));
  }
);

server.listen(port, '127.0.0.1', () => {
  console.log(`web-compat TLS fixture server listening on https://127.0.0.1:${port} (requestCert: true)`);
});
