// Regenerate the README download section for a release version.
// Usage: node scripts/update-readme.mjs [version|vX.Y.Z]
// With no argument, uses the current package.json version — this is how the `version`
// npm-lifecycle hook runs it during RELEASE-PREP, folding the download-link bump into the
// same commit that bumps the version (see docs/RELEASING.md). No longer run by CI.
import { readFileSync, writeFileSync } from 'node:fs';

const argVersion = (process.argv[2] || '').replace(/^v/, '').trim();
const version = argVersion || JSON.parse(readFileSync('package.json', 'utf8')).version;
if (!/^\d+\.\d+\.\d+$/.test(version)) {
  console.error('usage: update-readme.mjs [version]  (e.g. 0.2.0); with no arg, uses package.json version');
  process.exit(1);
}

const REPO = 'msieurthenardier/goldfinch';
const base = `https://github.com/${REPO}/releases/download/v${version}`;

const block = `<!-- DOWNLOADS:START (auto-generated by scripts/update-readme.mjs — do not edit by hand) -->
Grab the latest installer from the
**[Releases page »](https://github.com/${REPO}/releases/latest)**,
or download **v${version}** directly:

| Platform | Installer |
|----------|-----------|
| **Windows** | [Goldfinch Setup ${version}.exe](${base}/Goldfinch-Setup-${version}.exe) |
| **macOS** (Apple Silicon) | [Goldfinch-${version}-arm64.dmg](${base}/Goldfinch-${version}-arm64.dmg) · [.zip](${base}/Goldfinch-${version}-arm64-mac.zip) |
| **Linux** | [Goldfinch-${version}.AppImage](${base}/Goldfinch-${version}.AppImage) · [.deb](${base}/goldfinch_${version}_amd64.deb) |

> Builds are currently **unsigned**, so the first launch shows a Gatekeeper
> (macOS) / SmartScreen (Windows) warning — allow it through to run. macOS
> builds are Apple Silicon only for now.
<!-- DOWNLOADS:END -->`;

const readme = readFileSync('README.md', 'utf8');
const re = /<!-- DOWNLOADS:START[\s\S]*?<!-- DOWNLOADS:END -->/;
if (!re.test(readme)) {
  console.error('README.md is missing the <!-- DOWNLOADS:START --> ... <!-- DOWNLOADS:END --> markers');
  process.exit(1);
}
writeFileSync('README.md', readme.replace(re, block));
console.log(`README download section updated to v${version}`);
